pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                echo 'Build Starts!'
                bat "\"C:/Program Files/dotnet/dotnet.exe\" restore \"C:\Projects\MicroBackend\MicroBackend\MicroBackend.Gateway.Api\MicroBackend.Gateway.Api.csproj\""
                bat "\"C:/Program Files/dotnet/dotnet.exe\" build \"C:\Projects\MicroBackend\MicroBackend\MicroBackend.Gateway.Api\MicroBackend.Gateway.Api.csproj\""
                echo 'Build Ends'
            }
        }
		
	stage('Gateway Deploy') {
            steps {
                echo 'Deploy Starts!'
                bat "\"C:/Program Files/dotnet/dotnet.exe\" publish \"C:\Projects\MicroBackend\MicroBackend\MicroBackend.Gateway.Api\" --output \"C:/WebApis/ApiGateway\""
                echo 'Deploy Ends'
            }
        }		
       
    }
}
